Setting port to nil.
Might help with errors such as

SocketError: Failed to open TCP connection to maps.googleapis.com:443
(getaddrinfo: Name or service not known)

Additionally adding test (which caused some refactors around API key).